[tool.poetry]
    name         = "factorio-iac"
    version      = "0.1.0"
    description  = "Factorio Infrastructure as Code"
    license      = "MIT"
    readme       = "README.md"
    authors      = ["Nathan Vaughn <nath@nvaughn.email>"]
    homepage     = "https://github.com/https://github.com/NathanVaughn/factorio-iac"
    repository   = "https://github.com/https://github.com/NathanVaughn/factorio-iac.git"
    package-mode = false

[tool.poetry.dependencies]
    # Ubuntu 22.04 has python 3.10
    python            = "^3.10"
    jinja2            = "^3.1.4"
    python-dotenv     = "^1.0.1"
    pyinfra           = "^3.1"
    pulumi-aws        = "^6.51.0"
    pulumi-cloudflare = "^5.37.1"

[tool.poetry.group.dev.dependencies]
    pre-commit = "3.8.0"

[tool.pyright]
    typeCheckingMode           = "basic"
    venvPath                   = "."
    venv                       = ".venv"
    reportMissingParameterType = true

[build-system]
    requires      = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"
