[tool.poetry]
    name        = "factorio-iac"
    version     = "0.1.0"
    description = "Factorio Infrastructure as Code"
    license     = "MIT"
    readme      = "README.md"
    authors     = ["Nathan Vaughn <nath@nvaughn.email>"]
    homepage    = "https://github.com/https://github.com/NathanVaughn/factorio-iac"
    repository  = "https://github.com/https://github.com/NathanVaughn/factorio-iac.git"
    package-mode = false

[tool.poetry.dependencies]
    python = "^3.12"

[tool.poetry.group.dev.dependencies]
    pre-commit = "3.8.0"

[tool.pyright]
    typeCheckingMode           = "basic"
    venvPath                   = "."
    venv                       = ".venv"
    reportMissingParameterType = true

[build-system]
    requires      = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"