name: Pulumi

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main

env:
  # Use the same ssh-agent socket value across all jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install vscode-task-runner
        run: uv tool install vscode-task-runner

      - name: Get Pulumi Version
        id: pulumi_version
        run: echo "pulumi_version=$(python scripts/get_pulumi_version.py)" >> "$GITHUB_OUTPUT"

      - name: Install Pulumi
        uses: pulumi/actions@v6
        with:
          pulumi-version: ${{ steps.pulumi_version.outputs.pulumi_version }}

      - name: Setup secrets
        run: echo '${{ secrets.CONFIG_FILE }}'' > config.py

      - name: Setup SSH Key
        if: github.event_name == 'push'
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Install dependencies
        run: vtr install

      - name: Pulumi Preview
        if: contains(github.event_name, 'pull_request')
        run: vtr preview --expect-no-changes

      - name: Pulumi Update
        if: github.event_name == 'push'
        run: vtr deploy